[manifest]
version = "1.0.0"
dump_lua = true
priority = 777


[[patches]]
[patches.pattern]
target = '=[SMODS SixSuits "SixSuits.lua"]'
pattern = '''
return {
	vars = { '' .. (G.GAME and G.GAME.probabilities.normal or 1), card.ability.extra.odds }
}
'''
position = "at"
payload = '''
local probvars = {SMODS.get_probability_vars(card, 1, card.ability.extra.odds)}
return {vars = {probvars[1], probvars[2]}}
'''
match_indent = true
overwrite = true

[[patches]]
[patches.pattern]
target = '=[SMODS SixSuits "SixSuits.lua"]'
pattern = '''
pseudorandom('starruby') < G.GAME.probabilities.normal / card.ability.extra.odds then
'''
position = "at"
payload = '''
SMODS.pseudorandom_probability(card, 'starruby', 1, card.ability.extra.odds) then
'''
match_indent = true
overwrite = true

[[patches]]
[patches.pattern]
target = '=[SMODS SixSuits "SixSuits.lua"]'
pattern = '''
if v:is_suit(moon_suit.key) and not (v.ability.name == 'Glass Card') and pseudorandom('moonstone') < G.GAME.probabilities.normal / card.ability.extra.odds then
'''
position = "at"
payload = '''
if v:is_suit(moon_suit.key) and not (v.ability.name == 'Glass Card') and SMODS.pseudorandom_probability(card, 'moonstone', 1, card.ability.extra.odds) then
'''
match_indent = true
overwrite = true

[[patches]]
[patches.pattern]
target = '=[SMODS allinjest "Items/Consumables/Planets/paper_weywot.lua"]'
pattern = '''
if next(SMODS.find_mod("Bunco")) then
	paper_weywot_planet.config.hand_type = string.gsub(paper_weywot_planet.config.hand_type, "paperback", "bunc")
end
'''
position = "before"
payload = '''
if next(SMODS.find_mod("SpectrumAPI")) then
	paper_weywot_planet.config.hand_type = "spa_Spectrum"
end
'''
match_indent = true
overwrite = true

[[patches]]
[patches.pattern]
target = '=[SMODS allinjest "Items/Consumables/Planets/paper_ilmare.lua"]'
pattern = '''
if next(SMODS.find_mod("Bunco")) then
	paper_ilmare_planet.config.hand_type = string.gsub(paper_ilmare_planet.config.hand_type, "paperback", "bunc")
end
'''
position = "before"
payload = '''
if next(SMODS.find_mod("SpectrumAPI")) then
	paper_ilmare_planet.config.hand_type = "spa_Spectrum_House"
end
'''
match_indent = true
overwrite = true

[[patches]]
[patches.pattern]
target = '=[SMODS allinjest "Items/Consumables/Planets/paper_ixion.lua"]'
pattern = '''
if next(SMODS.find_mod("Bunco")) then
	paper_ixion_planet.config.hand_type = string.gsub(paper_ixion_planet.config.hand_type, "paperback", "bunc")
end
'''
position = "before"
payload = '''
if next(SMODS.find_mod("SpectrumAPI")) then
	paper_ixion_planet.config.hand_type = "spa_Spectrum"
end
'''
match_indent = true
overwrite = true

[[patches]]
[patches.pattern]
target = '=[SMODS allinjest "Items/Consumables/Planets/paper_mk2.lua"]'
pattern = '''
if next(SMODS.find_mod("Bunco")) then
	paper_mk2_planet.config.hand_type = string.gsub(paper_mk2_planet.config.hand_type, "paperback", "bunc")
end
'''
position = "before"
payload = '''
if next(SMODS.find_mod("SpectrumAPI")) then
	paper_mk2_planet.config.hand_type = "spa_Spectrum_Five"
end
'''
match_indent = true
overwrite = true

[[patches]]
[patches.pattern]
target = '=[SMODS allinjest "Items/Consumables/Planets/paper_salacia.lua"]'
pattern = '''
if next(SMODS.find_mod("Bunco")) then
	paper_salacia_planet.config.hand_type = string.gsub(paper_salacia_planet.config.hand_type, "paperback", "bunc")
end
'''
position = "before"
payload = '''
if next(SMODS.find_mod("SpectrumAPI")) then
	paper_salacia_planet.config.hand_type = "spa_Spectrum_Five"
end
'''
match_indent = true
overwrite = true

[[patches]]
[patches.pattern]
target = '=[SMODS allinjest "Items/Consumables/Planets/paper_varda.lua"]'
pattern = '''
if next(SMODS.find_mod("Bunco")) then
	paper_varda_planet.config.hand_type = string.gsub(paper_varda_planet.config.hand_type, "paperback", "bunc")
end
'''
position = "before"
payload = '''
if next(SMODS.find_mod("SpectrumAPI")) then
	paper_varda_planet.config.hand_type = "spa_Spectrum_House"
end
'''
match_indent = true
overwrite = true

[[patches]]
[patches.pattern]
target = '=[SMODS allinjest "Items/Consumables/Planets/paper_hiiaka.lua"]'
pattern = '''
if next(SMODS.find_mod("Bunco")) then
	paper_hiiaka_planet.config.hand_type = string.gsub(paper_hiiaka_planet.config.hand_type, "paperback", "bunc")
end
'''
position = "before"
payload = '''
if next(SMODS.find_mod("SpectrumAPI")) then
	paper_hiiaka_planet.config.hand_type = "spa_Straight_Spectrum"
end
'''
match_indent = true
overwrite = true

[[patches]]
[patches.pattern]
target = '=[SMODS allinjest "Items/Consumables/Planets/paper_namaka.lua"]'
pattern = '''
if next(SMODS.find_mod("Bunco")) then
	paper_namaka_planet.config.hand_type = string.gsub(paper_namaka_planet.config.hand_type, "paperback", "bunc")
end
'''
position = "before"
payload = '''
if next(SMODS.find_mod("SpectrumAPI")) then
	paper_namaka_planet.config.hand_type = "spa_Straight_Spectrum"
end
'''
match_indent = true
overwrite = true

[[patches]]
[patches.pattern]
target = '=[SMODS stacked "code/hooks.lua"]'
pattern = '''
local ret = hookTo(x, y)
'''
position = "at"
payload = '''
local ret = hookTo and hookTo(x, y) or nil
'''
match_indent = true
overwrite = true