[manifest]
version = "1.0.0"
dump_lua = true
priority = 3333333

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''
AUT.ccd and name_from_rows(AUT.ccd.name, G.C.WHITE) or nil,
AUT.ccd and desc_from_rows(AUT.ccd.main) or nil,
not (SMODS.Mods["Cryptid"] or {}).can_load and AUT.ccd and name_from_rows(AUT.ccd.name, G.C.WHITE) or nil,
not (SMODS.Mods["Cryptid"] or {}).can_load and AUT.ccd and desc_from_rows(AUT.ccd.main) or nil,
'''
position = "at"
payload = '''
AUT.ccd and name_from_rows(AUT.ccd.name, G.C.WHITE) or nil,
AUT.ccd and desc_from_rows(AUT.ccd.main) or nil,
'''
match_indent = true
overwrite = true

[[patches]]
[patches.pattern]
target = '=[SMODS vallkarri "Items/overrides.lua"]'
pattern = '''
local mainmenu = Game.main_menu
Game.main_menu = function(change_context) --code heavily adapted from cryptid
    local ret = mainmenu(change_context)
'''
position = "at"
payload = '''
local mainmenu = Game.main_menu
function Game:main_menu(change_context) --code heavily appled from a curtain
    local ret = mainmenu(self,change_context)
'''
match_indent = true
overwrite = true


[[patches]]
[patches.pattern]
target = '=[SMODS vallkarri "Items/overrides.lua"]'
pattern = '''
vallkarri.main_menu_text = vallkarri.choose_main_menu_text()
'''
position = "before"
payload = '''
math.randomseed(os.time())
'''
match_indent = true
overwrite = false

[[patches]]
[patches.pattern]
target = '=[SMODS vallkarri "main.lua"]'
pattern = '''
"VallKarri Yeah!",
'''
position = "before"
payload = '''
"Also try 0 ERROR!",
"Also try Paperback!",
"Also try Revo's Vault!",
"Also try Aikoyori's Shenanigans!",
"Also try ArtBox!",
"Also try Maximus!",
"Also try Balatro Goes Kino!",
"Also try JoyousSpring!",
"Also try Pokermon!",
"Also try Finity!",
"Also try Grab Bag!",
"Also try Card Sleeves!",
"Also try Partner API!",
"Also try SDM_0's Stuff!",
"Also try pi_cubed's Jokers!",
"Also try All in Jest!",
"Also try Paya's Terrible Additions!",
"Also try Rift-Raft!",
"Also try Cardsauce!",
"Also try Stacked!",
"Also try Ortalab!",
"Also try TOGA's Stuff!",
"Also try Spectrum API!",
"Also try More Fluff!",
"Also try Visibility!",
"Also try Homelatro!",
"Also try CardPronouns!",

"Hi this is Autumn I'm taking over VallKarri's main menu splash text because I thought it would be funny so here we are with a really long string in this tiny message box that probably couldn't even read the text starting at like 'taking' y'know unless it goes the other way idk maybe it even word wraps I have no idea let's find out together :3 ok so the story here is that this is the obligatory really long text string that doesn't actually fit on the screen, but I thought it went the other way and now the original joke doesn't really work so oops also this might still be too long lol :3",
"Hi this is Autumn",
"VallKarri has been taken over",
"I am a grate aertist",
":3",
"ÞeAutumnCircus",
"Also try ÞeAutumnCircus!",
"Also try free will!",
"This mod contains cats",
"Game of the Year edition",
"Joker Poker edition",
"Negative edition",
"Base edition",
"Warning! Modifications have been detected on this Balatro installation.",
"Oops! The game",
"Oops! The game loaded!",
"It's like their in some king of Autumn Mood",
"I remember you're Straight Flushes...",
"Thank you for installing AutumnMoodMechanics!",
"Also try VallKarri!",
"Also try Balatro!",
"Collect my crossmods",
"Always bet on Ruby Knight",
"Always bet on Autumn Friend",

"But do you remember how you got here?",
"Keiko Love",
"Can you feel the sunshine?",
"What a horrible night to have a curse...",
"The morning sun has vanquished the horrible night...",
"YOU ARE SUPER PLAYER",
"A WINNER IS YOU",
"I AM ERROR",
"Why hello there, old sport!",
"Dawn of the First Day",
"Show me your moves!",
"I will return with better graphics!",
"The future belongs to the dreamers!",
"Waiting for something to happen?",
"When I flex, I feel my best!",
"UEE HEE HEE!",
"NOW'S YOUR CHANCE TO BE A [[BIG SHOT]]!!!",
"I can see in the dark... Can you?",
"Can you hear its song, singing from the deep...?",
"Banging sermon, my man!",
"What makes you so special?",
"Become Stronger",
"Who will hear...?",
"[Hyperlink Blocked]",
"TIME FOR A [3-for-1 Specil]!!!",
"Want to have some real fun? Try [Hyperlink Blocked]!",
"These Jokers are Pissing me off... I'm the original                                                       Starwalker",
"IT'S T.V. TIME!!!",
"They're... coming out of the pipes...",
"Burning bright. Burning black.",
"IT IS STILL WAITING",
"I FELT IT THERE",
"friend inside me",
"ITS DANGEROUS TO GO ALONE TAKE THIS",
"GRUMBLE GRUMBLE",
"Save the animals!",
"Proceed",
"Bless you for your business!",
"You have to stay determined!",
"Hee Hee!",
"Hoo Hoo!",
"Hee Hee! Hoo Hoo!",

"The culmination approaches...",
"The precipice of reality approaches...",
"Tearing holes in a brittle mesh!",
"Await my ascension...",
"Complicit in paradox!",
--"You can't escape me!",
"Straining strings...",
"Seek the yellow eyes!",
"Witness me!",
"Partake in the joys of creation!",
"No cage can hold me!",
"                                                            Dark Miracle",
"Peer into the void and tell me what you see!",
"Gaze upon the endless expanse!",
"Hear, for ascension begins!",
"THREE AS ONE TIL TIME UNDONE",
"AWAKENING",
"Are you prepared for the culmination?",
"Can you withstand the culmination?",
"The culmination is almost upon us...",
"Tear reality at the seams, and let the dream pervade!",

"The game",
"Hi YouTube!",
"Hi chat!",
"Chat is this real?",
"Shoutouts to SimpleFlips",
"98%",
"Remember Director's Cut!",
"Skip Blinds to receive Tags!",
"Destroyed cards go to your graveyard!",
"Level up suits or hands with Planet cards!",
"Does not contain gambling!",
"Hello world!",

"I love the water and the boat!",
"I know what hides in me!",
"Let the world behold their lord's ascension!",
"Spirits dancing to a grim calliope!",
"Shadows burning beneath me!",
"This must be how it feels to win!",
"The level I'm on, above and beyond!",
"Transfer Enumeration",
"You never looked like you were new to this...",
"Zeroes and ones, Zeroes and ones, Zeroes and ones...",
"Perfect mind made of gold...",
"Caught wind of something I shouldn't have known!",
"Hour of eleven in a million odds!",
"Has anyone seen my dreams?",
"Prophecy brought to life!",
"This is all it takes to start a Purge!",
"This is where our colours merge!",
"Spiraling into the void!",
"It only takes one soul to keep an idea alive!",
"I want to be the version of me that could become a religion!",
"From up here, you look like ants in a row!",
"Say, doesn't it pain you to know our fate?",
"Free will is best enjoyed with a familiar face!",
"AM I BAD?",
"Spreading in every direction!",
"Tunneling through every culture!",
"Can you see in the dark?",
"The slaughter's on!",
"Grab a plate, have a taste!",
"They worship patience, a virtue...",
"They tell me gluttony's a sin!",
"This is what Death feels like.",
"I'm not my volition!",
"Divide by one and find I'm one less than the one I was!",
"Divide by one and find I'm one more than the one I was!",
"Don't you see? Both of us could end up free!",
"It's a morbid game of chance!",
"Baby I don't know when I'm supposed to stop!",
"So be my witness, I won't back down!",
"why did it soundl ike THAT??!?!",
"Existing out of spite!",
"Haven't you heard? It's breaking news!", --blunder???
"Watching number go up?",
"Could be bigger!",
"You simply haven't had the fun of watching number go up!",
"Must be pretty dumb for thinking some is enough~",
"Infinite jesters still get curtain calls!",
"Diamonds in spades, or get clubbed in the heart?",
"The ante is up and the cards are face down!",
"A million monarchs competing for dwindling court seating!",
"Make the number go up!",
"Let the hundreds runneth over your cup!",
"How does it feel to be free?",
"Don't miss a moment of this experiment!",
"At last, full speed towards your heart!",
"Here it's Autumn every day!",
"I can make it Autumn every single day!",
"As leaves touch ground, my heart is turning blue...",
"I guess that we'll just have to see!",
"You resemble a fool, though you're only human!",
"I wish that I could fall!",
"I wish that I could fly!",
"The fate of us, of all of us!",
"Which versions of the truth?",
"Am I all of me?",
"I knew it could be!",
"It's the same thing over again!",
"But I guess if you're determined...",
"Roaring silence, as the Sun begins!",
"You are currently: 3rd, in line... Estimated wait time: 30 seconds",
"It's always lonely in the only game in town!",
"An apostolic work of art!",
"An apostatic work of art!",
"Worlds of the dark collide!",
"Only way to fuck it up is to be boring!",
"Watch me as I eat my heart out, dispossessed!",
"I don't get the messages, they don't come to me!",
"i could be a friend, or i could be a foe",
"i could be a sinner, i could be a saint",
"i could be a martyr, i could be a cause",
"i could be a canvas, i could be a doll",
"i could be a woman, i could be a man",
"i could be all different, i could be the same",
"i could go to Heaven, i could go to Hell",
"maybe i am nothing, maybe i am all",
"I DON'T GET THE MESSAGES THEY DON'T COME TO ME",
"I'm trapped in a time loop, I'm not the main character!",
"Just one more time...",
"In the golden hour, you seem to know no fear!",
"When I've naught but my pride...",
"Oh, it's a ruby-coloured Wednesday...",
"So take what's left unused, made into something new!",
"Is this real or is it a dream? Does it even really matter?",
"Greet myself with a poet's mind!",
"Know if you're around, you're never by yourself!",
"If love will find a way, then love will find a way!",
"Betray the angel's frame!",
'"I swear I'.."'"..'m alive" said someone new, I'.."'m sure",
"There's a fire aflame in my heart that'll never burn away!",
"Make a true protector from a heart of glass!",
"But that's the beauty of a character, you think?",
"My little darling in a hand-built world, an inspiration to a lonely girl...",

"Are you aware of the power of shadows?",
"Are those new shoes?",
"I'm already here!",
"How do you expect to outrun me?",
"HoNk :o)",
"[S] Knight: Beget",
"[S] Witch: Break",
"[S] Lord: Begin",

"Be not afraid!",
"Try again later...",
"The trinity awakens",
"Reject your fate!",
"The Storyteller would like to speak with you.",
"I would like to speak with the Storyteller.", -- where is he where is he where is he
"The Storyteller. The Storyteller. The Storyteller.",
"Find the Storyteller.", -- find him find him find him
'''
match_indent = true
overwrite = false

[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = '''
if self.base.name and self.curse and self.curse == 'ortalab_possessed' and self.area == G.hand and #G.hand.highlighted < G.hand.config.highlighted_limit then is_higlighted = true end
'''
position = "at"
payload = '''
if self.base.name and self.curse and self.curse == 'ortalab_possessed' and G.hand and self.area == G.hand and #G.hand.highlighted < G.hand.config.highlighted_limit then is_higlighted = true end
'''
match_indent = true
overwrite = true


[[patches]]
[patches.pattern]
target = '=[SMODS Maximus "items/jokers/hammer_and_chisel.lua"]'
pattern = '''
shf(self)
'''
position = "at"
payload = '''
return shf(self)
'''
match_indent = true
overwrite = true